version: "3"

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    entrypoint: "./entrypoint.sh"
    ports:
      - "8080:8080"
    env_file:
      - .env_$ENVIRONMENT
    volumes:
      - .:/app
