# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ ci ]
  pull_request:
    branches: [ main release]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build the app
        run: make install

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/ci'
    steps:
    - uses: actions/checkout@v1

#    - name: Build and deploy to Heroku
#      env:
#        ENVIRONMENT: prod
#      run: |
#        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
#        git push heroku HEAD:ci -f
#        docker-compose -p localrunner -f docker-compose.yml down
#        docker-compose -p localrunner -f docker-compose.yml build
#        docker-compose -p localrunner -f docker-compose.yml up



    - name: Login to Heroku Container registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
#        HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      run: heroku container:login
#      run: echo ${HEROKU_API_KEY} | docker login --username=${HEROKU_EMAIL} registry.heroku.com --password-stdin

    - name: Create app
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: evfocustool
      run: heroku create ${HEROKU_APP_NAME}

    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: evfocustool
      run: heroku container:push -a ${HEROKU_APP_NAME} web
#      run: docker build . --file Dockerfile --tag registry.heroku.com/${HEROKU_APP_NAME}/web


    - name: Release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: evfocustool
      run: heroku container:release -a ${HEROKU_APP_NAME} web
#      run: heroku container:run -a ${HEROKU_APP_NAME} web